version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    # 1. Instala todas las deps de docs (incluyendo sphinx)
    - pip install --no-cache-dir -r requirements-docs.txt
    # 2. Instala tu paquete
    - pip install --no-cache-dir -e .
    # 3. Genera los .rst sin backslashes
    - sphinx-apidoc --force --separate --module-first -o docs/source/protocolo protocolo

sphinx:
  configuration: docs/source/conf.py
