version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install --no-cache-dir -r requirements-docs.txt
    - pip install --no-cache-dir -e .
    - mkdir -p docs/source/modules
    - sphinx-apidoc -o docs/source/modules protocolo --force --module-first
    # Añadir :member-order: bysource a los .rst generados
    - |
      for file in docs/source/modules/*.rst; do
        if grep -q ":members:" "$file"; then
          grep -q ":member-order: bysource" "$file" || \
          sed -i "/:members:/a \ \  :member-order: bysource" "$file"
        else
          sed -i "/^\.\. automodule::/a \ \ :members:\n\ \ :member-order: bysource" "$file"
        fi
      done
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py





