version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends libgdal-dev
    - gdal-config --version  # Esto intentará verificar la instalación
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: requirements-docs.txt