version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"

# 👇 Elimina `commands` para que Read the Docs use el flujo estándar
# (assume que conf.py y index.rst ya están bien configurados)

sphinx:
  configuration: docs/source/conf.py

