version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    - pip install -e .    
    - python -m sphinx.ext.apidoc --force --separate --module-first \
        -o docs/source/protocolo protocolo

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements-docs.txt
