version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    - pip install --no-cache-dir -r requirements-docs.txt
    - pip install --no-cache-dir -e .
    - mkdir -p docs/source/modules  # subcarpeta limpia para los rst
    - sphinx-apidoc --force --separate --module-first -o docs/source/modules protocolo


sphinx:
  configuration: docs/source/conf.py

