version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    # instala tu paquete (editable) para que autodoc lo importe
    - pip install -e .
    # genera automáticamente un rst por cada módulo en tu paquete
    - sphinx-apidoc --force --separate --module-first \
        -o docs/source/protocolo protocolo

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements-docs.txt