version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    - pip install --no-cache-dir -r requirements-docs.txt
    - pip install --no-cache-dir -e .
    - mkdir -p docs/source/modules
    - sphinx-apidoc -o docs/source/modules protocolo --force --module-first
    - ls -la docs/source/modules
    - cat docs/source/modules/modules.rst
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py



