version: 2.2.3
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  commands:
    - sudo apt-get update
    - sudo apt-get install -y libgdal-dev
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: requirements-docs.txt